version: "3.8"

services:
  mocut-backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
      args:
        BACKEND_TAG: ${BACKEND_TAG}
    image: ${APP_NAME}-backend:${BACKEND_TAG}
    container_name: mocut-backend
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: ${APP_NAME}-backend
      SERVICE_TAGS: dev
      DB_CONNECTION: pgsql
      DB_HOST: mocut-postgres
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    working_dir: /app
    volumes:
      - ./apps/backend:/app
      - ./apps/backend/docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
      - "${UDP_PORT}:443/udp"
    networks:
      - mocut-network
    env_file:
      - .env
    depends_on:
      - mocut-postgres

  mocut-postgres:
    image: postgres:${POSTGRES_TAG}
    container_name: mocut-postgres
    restart: unless-stopped
    tty: true
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
    networks:
      - mocut-network
    env_file:
      - .env

  mocut-frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
      args:
        FRONTEND_TAG: ${FRONTEND_TAG}
    image: ${APP_NAME}-frontend:${FRONTEND_TAG}
    container_name: mocut-frontend
    ports:
      - "${FRONTEND_PORT}:4200"
    environment:
      NODE_ENV: development
    volumes:
      - ./apps/frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - mocut-network
    env_file:
      - .env

networks:
  mocut-network:
    name: mocut-network
    driver: bridge
