version: "3.8"

services:
  mocut-frontend:
    build:
      context: .
      args:
        FRONTEND_TAG: ${FRONTEND_TAG}
      dockerfile: Dockerfile
    image: ${APP_NAME}-frontend:${FRONTEND_TAG}
    container_name: mocut-frontend
    ports:
      - "${FRONTEND_PORT}:4000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start
    networks:
      - mocut-network
    env_file:
      - ../../.env

networks:
  mocut-network:
    name: mocut-network
    driver: bridge
