version: "3.8"

services:
  mocut-backend:
    build:
      context: .
      args:
        BACKEND_TAG: ${BACKEND_TAG}
    image: ${APP_NAME}-backend:${BACKEND_TAG}
    container_name: mocut-backend
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: ${APP_NAME}-backend
      SERVICE_TAGS: dev
      DB_CONNECTION: pgsql
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - mocut-network
    env_file:
      - ../../.env

  mocut-postgres:
    image: postgres:${POSTGRES_TAG}
    container_name: mocut-postgres
    restart: unless-stopped
    tty: true
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    networks:
      - mocut-network
    env_file:
      - ../../.env

networks:
  mocut-network:
    name: mocut-network
    driver: bridge
